// <auto-generated />
namespace Capstone.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Section4Cleanup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Section4Cleanup));
        
        string IMigrationMetadata.Id
        {
            get { return "201405101751168_Section4-Cleanup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
