// <auto-generated />
namespace Capstone.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class MergeSection3ToForm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MergeSection3ToForm));
        
        string IMigrationMetadata.Id
        {
            get { return "201405170049045_MergeSection3ToForm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
